PIXEL_VALUE_RANGE: int = 256
MAX_PIXEL_VALUE: int = PIXEL_VALUE_RANGE - 1
WHITE: int = MAX_PIXEL_VALUE
BLACK: int = 0

HISTOGRAM_BG: int = WHITE
HISTOGRAM_FG: int = 150
HISTOGRAM_HEIGHT: int = 256

DEBUG_MODE: bool = 1